# Generated by Django 3.2.7 on 2021-10-08 21:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saas_account', '0003_domain_site_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicator', models.CharField(choices=[('major', 'major'), ('minor', 'minor'), ('none', 'none'), ('critical', 'critical')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('zoom_uppdated_at', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
