# Generated by Django 3.2.7 on 2021-10-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_account', '0006_slack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slack',
            name='active_incidents',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
