# Generated by Django 3.2.7 on 2021-10-22 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saas_account', '0010_auto_20211021_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miro',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='slack',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trello',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='zoom',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
